<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Url;
use Drupal\Core\Link;
// $Id$
// UMS cardfile module will provide for adding, editing and querying of records into the UMS card file

/**
 * Display help and module information
 * @return help text for section
 */
function ums_cardfile_help($path, $arg) {
  $output = '';

  switch ($path) {
  case "admin/help#ums_cardfile":
    $output = '<p>' .  t("UMS Card File CRUD Interface") . '</p>';

    break;
  }

  return $output;
}


/**
 * Valid permissions for UMS modules
 * @return array of valid permissions
 * need to change all permissions to a UMS only role
 */
function ums_cardfile_perm() {
  return array('edit ums card file records', 'view ums card file records' );
}


/**
 * Implements hook_theme().
 *
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a particular render array is to be rendered as HTML.
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 *
 * If you change this method, clear theme registry and routing table 'drush cc theme-registry' and 'drush cc router'.
 */
function ums_cardfile_theme($existing, $type, $theme, $path) {
  return [
    'ums-cardfile-home' => [
      'variables' => [
      ]
    ],
    'ums-cardfile-artists' => [
      'variables' => [
        'artists' => NULL,
        'pager' => NULL,
        'filter' => NULL,
        'base_url' => $GLOBALS['base_url']
      ]
    ],
    'ums-cardfile-artist' => [
      'variables' => [
      'artist' => NULL,
      ]
    ],
    'ums-cardfile-venues' => [
      'variables' => [
      'venues' => NULL,
      'venue_add_form' => NULL,
      ]
    ],
    'ums-cardfile-venue' => [
      'variables' => [
      'venue' => NULL,
      ]
    ],
    'ums-cardfile-events' => [
      'variables' => [
      'year' => NULL,
      'rows' => NULL,
      ]
    ],
    'ums-cardfile-event' => [
      'variables' => [
        'event' => NULL,
        'event_add_performance_form' => NULL,
      ]
    ],

    'ums-cardfile-series' => [
      'variables' => [
        'series' => NULL,
        'series_add_form' => NULL,
      ]
    ],

    'ums-cardfile-works' => [
      'variables' => [
        'works' => NULL,
        'pager' => NULL,
        'filter' => NULL,
        'base_url' => $GLOBALS['base_url']     ]
    ],
  ];
}


// DRUPAL 8 MIGRATION NEW METHODS
  /*
* Debugging routine to log to the <root folder>/LWKLWK.log IN arborcat.module
*/
function dblog(...$thingsToLog) {
  $lineToLog = '';
  foreach ($thingsToLog as $item) {
    $lineToLog = $lineToLog . ' ' . print_r($item, TRUE);
  }
  // prepend date/time onto log line
  $nowDateTime = new DrupalDateTime();
  $dateTimeString = (string) $nowDateTime->format('Y-m-d H:i:s');
  $completeLine = '[' . $dateTimeString . '] ' . $lineToLog . "\n";
  error_log($completeLine, 3, "LWKLWK.log");
}

function ums_cardfile_create_link($link_text, $url) {
  dblog('ums_cardfile_create_link entered, link_text. url =', $link_text, $url);
  $url = Url::fromUri('internal:/' . $url);
  $project_link = Link::fromTextAndUrl(t($link_text), $url);
  return $project_link->toString();
}

function ums_cardfile_save($table_name, $fields_array, $field_key) {
  $db = \Drupal::database();

  $keyValue = NULL;
  if ($field_key && $fields_array[$field_key]) {
    $keyValue = $fields_array[$field_key];
    unset($fields_array[$field_key]);
    $db->update($table_name)->fields($fields_array)->condition($field_key, $keyValue)->execute();
  }
  else {
    dblog('ums_cardfile_save: INSERT', $table_name, $fields_array);
    $pid = $db->insert($table_name)->fields($fields_array)->execute();
    dblog('ums_cardfile_save: AFTER INSERT', $pid);
  }
}

function ums_cardfile_drupal_goto($path, $options = []) {
  $url = Url::fromRoute($path, $options);
  dblog('ums_cardfile_drupal_goto: url=', $url->toString());

  return $url;
}

/*== ARTISTS =================================================================*/

function _ums_cardfile_get_artist($aid = 0) {
  dblog('_ums_cardfile_get_artist: ENTERED $aid:', $aid);
  $db = \Drupal::database();
  $artist = $db->query("SELECT ums_artists.aid AS aid, " .
                                    "ums_artists.name AS name, " .
                                    "ums_artists.name_plain AS name_plain, " .
                                    "ums_artists.alias AS alias, " .
                                    "ums_artists.notes AS notes, " .
                                    "ums_artists.photo_nid AS photo_nid " .
                                    "FROM ums_artists " .
                                    "WHERE ums_artists.aid = :aid", [':aid' => $aid])->fetchAssoc();

  // Get Works
  $works = $db->query("SELECT * " .
                  "FROM ums_artist_works, ums_work_roles, ums_works " .
                  "WHERE ums_artist_works.aid = :aid " .
                  "AND ums_artist_works.wrid = ums_work_roles.wrid " .
                  "AND ums_artist_works.wid = ums_works.wid " .
                  "ORDER BY ums_works.title ASC", [':aid' => $aid])->fetchAll(PDO::FETCH_ASSOC);
  
  foreach ($works as $work) {
    $artist['works'][] = $work;
  }

  // Get Performances
  $performances = $db->query("SELECT * " .
                  "FROM ums_artist_performances, ums_performance_roles, ums_performances, ums_events " .
                  "WHERE ums_artist_performances.aid = :aid " .
                  "AND ums_artist_performances.prid = ums_performance_roles.prid " .
                  "AND ums_artist_performances.pid = ums_performances.pid " .
                  "AND ums_performances.eid = ums_events.eid " .
                  "ORDER BY ums_events.date ASC", [':aid' => $aid])->fetchAll(PDO::FETCH_ASSOC);
  
  foreach ($performances as $perf) {
    $performance = _ums_cardfile_get_performance($perf['pid']);
    $performance['role'] = $perf['name'];
    $artist['performances'][] = $performance;
  }
  // Turn photo nid into links
  if ($artist['photo_nid']) {
    foreach (explode(',', $artist['photo_nid']) as $photo_nid) {
      $artist['photos'][] = ums_cardfile_create_link('Photo', 'node/' . $photo_nid);
    }
  }
  return $artist;
}

/*== PERFORMANCES ============================================================*/

function _ums_cardfile_get_performance($pid = 0) {
  dblog('_ums_cardfile_get_performance: ENTERED $aid:', $pid);
  $db = \Drupal::database();
  $performance = $db->query("SELECT ums_performances.pid AS pid, " .
                                    "ums_performances.eid AS eid, " .
                                    "ums_performances.wid AS wid, " .
                                    "ums_performances.notes AS notes, " .
                                    "ums_performances.youtube_url AS youtube_url," .
                                    "ums_performances.weight AS weight " .
                                    "FROM ums_performances " .
                                    "WHERE ums_performances.pid = :pid", [':pid' => $pid])->fetchAssoc();

  // Get performance event & work
  $performance['event'] = _ums_cardfile_get_event($performance['eid']);
  $performance['work'] = _ums_cardfile_get_work($performance['wid']);

  // Get performance artists
  $performance['artists'] = array();
  $perf_artists = $db->query("SELECT ums_artists.aid AS aid, " .
                  "ums_artists.name AS name, " .
                  "ums_artists.alias AS alias, " .
                  "ums_performance_roles.name AS role " .
                  "FROM ums_artist_performances, ums_artists, ums_performance_roles " .
                  "WHERE ums_artist_performances.pid = :pid " .
                  "AND ums_artist_performances.aid = ums_artists.aid " .
                  "AND ums_performance_roles.prid = ums_artist_performances.prid " .
                  "ORDER BY ums_artists.name ASC", [':pid' => $pid])->fetchAll(PDO::FETCH_ASSOC);
  
  foreach ($perf_artists as $perf_artist) {
    $performance['artists'][] = $perf_artist;
  }
  return $performance;
}

/*== EVENTS ==================================================================*/

function _ums_cardfile_get_event($eid = 0) {
  dblog('_ums_cardfile_get_event: ENTERED $eid:', $eid);
  $db = \Drupal::database();
  $event = $db->query("SELECT ums_events.eid AS eid, " .
                                   "ums_events.title AS title, " .
                                   "ums_events.date AS date, " .
                                   "ums_events.notes AS notes, " .
                                   "ums_events.program_nid AS program_nid, " .
                                   "ums_events.photo_nid AS photo_nid, " .
                                   "ums_events.youtube_url AS youtube_url," .
                                   "ums_series.sid AS sid, " .
                                   "ums_series.name AS series, " .
                                   "ums_venues.vid AS vid, " .
                                   "ums_venues.name AS venue " .
                                   "FROM ums_events, ums_series, ums_venues " .
                                   "WHERE ums_events.sid = ums_series.sid " .
                                   "AND ums_events.vid = ums_venues.vid " .
                                   "AND ums_events.eid = :eid", [':eid' => $eid])->fetchAssoc();
  // Get performances
  $performances = $db->query("SELECT * FROM ums_performances, ums_works " .
                  "WHERE ums_performances.eid = :eid " .
                  "AND ums_performances.wid = ums_works.wid " .
                  "ORDER BY ums_performances.weight ASC", [':eid' => $eid])->fetchAll(PDO::FETCH_ASSOC);

  $event['performances'] = [];
  foreach ($performances as $performance) {
    $event['performances'][] = $performance;
  }

  // Turn program nid into links
  dblog('_ums_cardfile_get_event: event =',$event);
  if ($event['program_nid']) {
    foreach (explode(',', $event['program_nid']) as $program_nid) {
      $program_nid = trim($program_nid);
      if (strpos($program_nid, '#') !== FALSE) {
        $parts = explode('#', $program_nid);
        $event['programs'][] = ums_cardfile_create_link(
          'Program',
          'node/' . $parts[0],
          array('fragment' => $parts[1])
        );
      } else {
        $event['programs'][] = ums_cardfile_create_link('Program', 'node/' . $program_nid);
      }
    }
  }

  // Turn photo nid into links
  if ($event['photo_nid']) {
    foreach (explode(',', $event['photo_nid']) as $photo_nid) {
      $event['photos'][] = ums_cardfile_create_link('Photo', 'node/' . $photo_nid);
    }
  }
  dblog('_ums_cardfile_get_event: EXITING'); 
  return $event;
}

/*== WORKS ===================================================================*/

function _ums_cardfile_get_work($wid = 0) {
  dblog('_ums_cardfile_get_work: ENTERED $wid:', $wid);
  $db = \Drupal::database();
  $work = $db->query("SELECT ums_works.wid AS wid, " .
                                  "ums_works.title AS title, " .
                                  "ums_works.alternate AS alternate, " .
                                  "ums_works.notes AS notes, " .
                                  "ums_works.youtube_url AS youtube_url " .
                                  "FROM ums_works " .
                                  "WHERE ums_works.wid = :wid", [':wid' => $wid])->fetchAssoc();

  if ($work['wid']) {
    // Get work artists
    $work['artists'] = array();
    $work_artists = db_query("SELECT ums_artists.aid AS aid, " .
                    "ums_artists.name AS name, " .
                    "ums_artists.alias AS alias, " .
                    "ums_work_roles.name AS role " .
                    "FROM ums_artist_works, ums_artists, ums_work_roles " .
                    "WHERE ums_artist_works.wid = :wid " .
                    "AND ums_artist_works.aid = ums_artists.aid " .
                    "AND ums_work_roles.wrid = ums_artist_works.wrid " .
                    "ORDER BY ums_artists.name ASC", [':wid' => $wid])->fetchAll(PDO::FETCH_ASSOC);

    foreach ($work_artists as $work_artist) {
      $work['artists'][] = $work_artist;
    }

    // Get work events
    $work['events'] = array();
    $work_events = $db->query("SELECT ums_events.eid AS eid, " .
                    "ums_events.date AS date, " .
                    "ums_events.notes AS notes, " .
                    "ums_events.youtube_url AS youtube_url," .
                    "ums_events.program_nid AS program_nid, " .
                    "ums_events.photo_nid AS photo_nid, " .
                    "ums_series.sid AS sid, " .
                    "ums_series.name AS series, " .
                    "ums_venues.vid AS vid, " .
                    "ums_venues.name AS venue, " .
                    "ums_performances.pid AS pid " .
                    "FROM ums_events, ums_series, ums_venues, ums_performances " .
                    "WHERE ums_events.sid = ums_series.sid " .
                    "AND ums_events.vid = ums_venues.vid " .
                    "AND ums_events.eid = ums_performances.eid " .
                    "AND ums_performances.wid = :wid " .
                    "ORDER BY ums_events.date ASC", [':wid' => $wid])->fetchAll(PDO::FETCH_ASSOC);

    foreach ($work_events as $work_event) {
      $work['events'][] = $work_event;
    }
  } else {
    $work = FALSE;
  }
  return $work;
}


/*== HELPER FUNCTIONS ========================================================*/
function ums_cardfile_searchadd($source_type, $source_id, $type, $search) {
  $output = '';
  if ($source_type == 'event') {
    $event = _ums_cardfile_get_event($source_id);
    $output .= '<h2>Adding repertoire to event: ' . $event['date'] . ' at ' . $event['venue'] . '</h2>';
  } elseif ($source_type == 'performance') {
    $performance = _ums_cardfile_get_performance($source_id);
    $role = db_fetch_object(db_query('SELECT * FROM ums_performance_roles WHERE prid = %d', $_GET['prid']));
    $query_args = array('prid' => $role->prid);
    $output .= '<h2>Adding a <strong>' . $role->name . '</strong> to ' . $performance['work']['title'] . ' at event: ' .
               $performance['event']['date'] . ' at ' . $performance['event']['venue'] . '</h2>';
  } elseif ($source_type == 'work') {
    $work = _ums_cardfile_get_work($source_id);
    $role = db_fetch_object(db_query('SELECT * FROM ums_work_roles WHERE wrid = %d', $_GET['wrid']));
    $query_args = array('wrid' => $role->wrid);
    $output .= '<h2>Adding a <strong>' . $role->name . '</strong> to ' . $work['title'] . '</h2>';
  }

  // Special Handling for copying performances from one event to another
  if (preg_match('/event:([\d]+)/', $search, $matches)) {
    $source_eid = $matches[1];
    $source_event = _ums_cardfile_get_event($source_eid);
    $output .= '<p>Copy Repertoire Performances from Event ' . $source_event['date'] . ' at ' . $source_event['venue'] . '?</p>';
    $output .= '<ul>';
    foreach ($source_event['performances'] as $source_perf) {
      $output .= '<li>' . $source_perf['title'] . '</li>';
    }
    $output .= '</ul><p>' . l('COPY PERFORMANCES TO THIS EVENT', "cardfile/join/$source_type/$source_id/source_event/$source_eid") . '</p>';
  } else {
    // Split search string into keywords
    $search_terms = explode(' ', str_replace(',', '', $search));
    $output .= '<p>Searching for "' . implode('" AND "', $search_terms) . '"</p>';
    $search_query_parts = array();
    $search_args = array();

    if ($type == 'work') {
      $wids = array();

      foreach ($search_terms as $search_term) {
        $search_query_part = "(ums_works.title LIKE '%%%s%%'";
        $works_search_args[] = $search_term;
        $artists_search_args[] = $search_term;
        $search_query_part .= " OR ums_works.alternate LIKE '%%%s%%'";
        $works_search_args[] = $search_term;
        $artists_search_args[] = $search_term;
        $search_query_part .= " OR ums_works.notes LIKE '%%%s%%'";
        $works_search_args[] = $search_term;
        $artists_search_args[] = $search_term;

        $works_query_parts[] = $search_query_part . ')';

        $search_query_part .= " OR ums_artists.name LIKE '%%%s%%'";
        $artists_search_args[] = $search_term;
        $search_query_part .= " OR ums_artists.name_plain LIKE '%%%s%%'";
        $artists_search_args[] = $search_term;
        $search_query_part .= " OR ums_artists.alias LIKE '%%%s%%'";
        $artists_search_args[] = $search_term;
        $search_query_part .= " OR ums_artists.notes LIKE '%%%s%%')";
        $artists_search_args[] = $search_term;

        $artists_query_parts[] = $search_query_part;
      }

      $res = db_query(
        "SELECT wid " .
                      "FROM ums_works " .
                      "WHERE " .
                      implode(' AND ', $works_query_parts) .
                      " ORDER BY wid",
        $works_search_args
      );
      while ($match = db_fetch_object($res)) {
        $wids[$match->wid] = $match->wid;
      }

      $res = db_query(
        "SELECT ums_works.wid AS wid " .
                      "FROM ums_works, ums_artist_works, ums_artists " .
                      "WHERE ums_works.wid = ums_artist_works.wid " .
                      "AND ums_artist_works.aid = ums_artists.aid " .
                      "AND " . implode(' AND ', $artists_query_parts) .
                      " ORDER BY wid",
        $artists_search_args
      );
      while ($match = db_fetch_object($res)) {
        $wids[$match->wid] = $match->wid;
      }

      if (count($wids)) {
        $works = array();
        $res = db_query("SELECT ums_works.wid as wid, " .
                        "ums_works.title as title, " .
                        "ums_works.alternate as alternate, " .
                        "ums_works.notes as notes, " .
                        "ums_works.youtube_url as youtube_url," .
                        "ums_artists.name as artist_name, " .
                        "ums_work_roles.name AS role " .
                        "FROM ums_works " .
                        "LEFT JOIN ums_artist_works ON ums_works.wid = ums_artist_works.wid " .
                        "LEFT JOIN ums_work_roles ON ums_artist_works.wrid = ums_work_roles.wrid " .
                        "LEFT JOIN ums_artists ON ums_artist_works.aid = ums_artists.aid " .
                        "WHERE ums_works.wid IN (" .
                        implode(',', $wids) .
                        ") ORDER BY ums_works.title");

        while ($match = db_fetch_object($res)) {
          if ($works[$match->wid]) {
            // Work data already captured, just add artist info
            $works[$match->wid]['Artists'] .= "<br /><strong>$match->role:</strong> $match->artist_name";
          } else {
            $works[$match->wid] = array(
              'Work ID' => $match->wid,
              'Title' => $match->title,
              'Alternate' => $match->alternate,
              'Artists' => "<strong>$match->role:</strong> $match->artist_name",
              'Notes' => $match->notes,
              'SELECT' => l('SELECT', "cardfile/join/$source_type/$source_id/work/" . $match->wid),
            );
          }
        }

        $output .= theme('table', array_keys(reset($works)), $works);
        $output .= '<p><strong>- OR -</strong></p>';
      } else {
        $output .= '<p>No existing repertoire matches found</p>';
      }

      $output .= '<p>' . l('ADD NEW REPERTOIRE', 'cardfile/work/edit', array('query' => array('eid' => $source_id, 'title' => $search))) . '</p>';
    } elseif ($type == 'artist') {
      foreach ($search_terms as $search_term) {
        $search_query_part = "(name LIKE '%%%s%%'";
        $search_args[] = $search_term;
        $search_query_part .= " OR name_plain LIKE '%%%s%%'";
        $search_args[] = $search_term;
        $search_query_part .= " OR alias LIKE '%%%s%%'";
        $search_args[] = $search_term;
        $search_query_part .= " OR notes LIKE '%%%s%%')";
        $search_args[] = $search_term;
        $search_query_parts[] = $search_query_part;
      }
      $res = db_query(
        "SELECT * FROM ums_artists " .
                      "WHERE " .
                      implode(' AND ', $search_query_parts) .
                      "ORDER BY name ASC",
        $search_args
      );

      $rows = array();
      while ($artist = db_fetch_array($res)) {
        $rows[] = array(
          'Artist ID' => $artist['aid'],
          'Name' => $artist['name'],
          'Alias' => $artist['alias'],
          'Notes' => $artist['notes'],
          'SELECT' => l(
            'SELECT',
            "cardfile/join/$source_type/$source_id/artist/" . $artist['aid'],
            array('query' => $query_args)
          ),
        );
      }
      $output .= theme('table', array_keys($rows[0]), $rows);
      $output .= '<p><strong>- OR -</strong></p>';
      if ($source_type == 'performance') {
        $source_id_name = 'pid';
      } elseif ($source_type == 'work') {
        $source_id_name = 'wid';
      }
      $output .= '<p>' . l('ADD NEW ARTIST', 'cardfile/artist/edit', array('query' => array($source_id_name => $source_id, 'name' => $search))) . '</p>';
    }
  }

  return $output;
}

function ums_cardfile_join($type1, $id1, $type2, $id2) {
  if ($type1 == 'event' && $type2 == 'source_event') {
    // Copy all performances from source_event to event
    $res = db_query("SELECT * FROM ums_performances WHERE eid = %d", $id2);
    while ($copy_perf = db_fetch_object($res)) {
      $copy_pid = $copy_perf->pid;
      unset($copy_perf->pid);
      $copy_perf->eid = $id1;
      drupal_write_record('ums_performances', $copy_perf);
      $res2 = db_query("SELECT * FROM ums_artist_performances WHERE pid = %d", $copy_pid);
      while ($copy_artist_perf = db_fetch_object($res2)) {
        $copy_artist_perf->pid = $copy_perf->pid;
        drupal_write_record('ums_artist_performances', $copy_artist_perf);
      }
    }
    drupal_set_message("All Performances copied from event $id2 to event $id1");
    drupal_goto('cardfile/event/' . $id1);
  }
  if ($type1 == 'event' && $type2 == 'work') {
    // New Performance
    $max = db_fetch_object(db_query("SELECT MAX(weight) as max_weight FROM ums_performances WHERE eid = %d", $id1));
    $perf = new stdClass;
    $perf->eid = $id1;
    $perf->wid = $id2;
    $perf->weight = $max->max_weight + 1;
    drupal_write_record('ums_performances', $perf);
    drupal_set_message('Created new Repertoire Performance for Event ID: ' . $id1 .
                       '<br />Add Artist Info below:');
    drupal_goto('cardfile/performance/' . $perf->pid);
  } elseif ($type1 == 'performance' && $type2 == 'artist') {
    $artist_perf = new stdClass;
    $artist_perf->pid = $id1;
    $artist_perf->aid = $id2;
    $artist_perf->prid = $_GET['prid'];
    drupal_write_record('ums_artist_performances', $artist_perf);
    drupal_set_message("Added new Repertoire Artist to the Performance");
    ums_cardfile_recent_artists($id2);
    drupal_goto('cardfile/performance/' . $artist_perf->pid);
  } elseif ($type1 == 'work' && $type2 == 'artist') {
    $artist_work = new stdClass;
    $artist_work->wid = $id1;
    $artist_work->aid = $id2;
    $artist_work->wrid = $_GET['wrid'];
    drupal_write_record('ums_artist_works', $artist_work);
    drupal_set_message("Added new Creator to the Repertoire");
    ums_cardfile_recent_artists($id2);
    drupal_goto('cardfile/work/' . $artist_work->wid);
  }
}

function ums_cardfile_autocomplete($type) {
  $search = strtolower($_GET['search']);
  if ($type == 'artist') {
    $res = db_query(
      "SELECT * FROM ums_artists " .
                    "WHERE name LIKE '%%%s%%' " .
                    "OR name_plain LIKE '%%%s%%' " .
                    "OR alias LIKE '%%%s%%' " .
                    "ORDER BY name ASC LIMIT 25",
      $search,
      $search,
      $search
    );
    while ($match = db_fetch_array($res)) {
      echo $match['name'] . ' (aid:' . $match['aid'] . ")\n";
    }
  } elseif ($type == 'event') {
    $res = db_query(
      "SELECT * FROM ums_events " .
                    "WHERE date LIKE '%%%s%%' " .
                    "ORDER BY date ASC LIMIT 25",
      $search
    );
    while ($match = db_fetch_array($res)) {
      $match_event = _ums_cardfile_get_event($match['eid']);
      echo $match_event['date'] . ' at ' . $match_event['venue'] . ' (eid:' . $match['eid'] . ")\n";
    }
  } elseif ($type == 'work') {
    $res = db_query(
      "SELECT * FROM ums_works " .
                    "WHERE title LIKE '%%%s%%' " .
                    "OR alternate LIKE '%%%s%%' " .
                    "OR notes LIKE '%%%s%%' " .
                    "ORDER BY title ASC LIMIT 25",
      $search,
      $search,
      $search
    );
    while ($match = db_fetch_array($res)) {
      echo $match['title'] . ' (wid:' . $match['wid'] . ")\n";
    }
  }
}

function ums_cardfile_recent_artists($new_aid = 0) {
  global $user;
  $artists = array();

  $var_key = 'ums_cardfile_recent_artists_' . $user->uid;

  $res = db_query('SELECT value FROM variable WHERE name = "%s"', $var_key);
  $row = db_fetch_object($res);
  if ($row->value) {
    $artists = unserialize($row->value);
    $existing_list = TRUE;
  }

  if ($new_aid) {
    // If already in the list, remove it
    if ($artists[$new_aid]) {
      $artist_name = $artists[$new_aid];
      unset($artists[$new_aid]);
    } else {
      $row = db_fetch_object(db_query("SELECT name FROM ums_artists WHERE aid = %d", $new_aid));
      $artist_name = $row->name;
    }

    // Add to the beginning of the list
    $artists = array_reverse($artists, TRUE);
    $artists[$new_aid] = $artist_name;
    $artists = array_reverse($artists, TRUE);

    // If > 20 elements, pop the last one off the list
    if (count($artists) > 20) {
      array_pop($artists);
    }

    // Store updated list
    if ($existing_list) {
      db_query(
        'UPDATE variable SET value = "%s" WHERE name = "%s"',
        serialize($artists),
        $var_key
      );
    } else {
      db_query(
        'INSERT INTO variable (name, value) VALUES ("%s", "%s")',
        $var_key,
        serialize($artists)
      );
    }
  }

  return $artists;
}

function ums_cardfile_normalize($string) {
  $a = 'ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûýýþÿŔŕ';
  $b = 'AAAAAAACEEEEIIIIDNOOOOOOUUUUYBSaaaaaaaceeeeiiiidnoooooouuuyybyRr';
  $string = utf8_decode($string);
  $string = strtr($string, utf8_decode($a), $b);

  return utf8_encode($string);
}
