<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Url;
use Drupal\Core\Link;

// $Id$
// UMS cardfile module will provide for adding, editing and querying of records into the UMS card file

/**
 * Display help and module information
 * @return help text for section
 */
function ums_cardfile_help($path, $arg) {
  $output = '';

  switch ($path) {
  case "admin/help#ums_cardfile":
    $output = '<p>' .  t("UMS Card File CRUD Interface") . '</p>';

    break;
  }

  return $output;
}


/**
 * Valid permissions for UMS modules
 * @return array of valid permissions
 * need to change all permissions to a UMS only role
 */
function ums_cardfile_perm() {
  return array('edit ums card file records', 'view ums card file records' );
}


/**
 * Implements hook_theme().
 *
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a particular render array is to be rendered as HTML.
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 *
 * If you change this method, clear theme registry and routing table 'drush cc theme-registry' and 'drush cc router'.
 */
function ums_cardfile_theme($existing, $type, $theme, $path) {
  return [
    'ums-cardfile-home' => [
      'variables' => [
      ]
    ],
    'ums-cardfile-artists' => [
      'variables' => [
        'artists' => NULL,
        'pager' => NULL,
        'filter' => NULL,
        'base_url' => $GLOBALS['base_url']
      ]
    ],
    'ums-cardfile-artist' => [
      'variables' => [
      'artist' => NULL,
      ]
    ],
    'ums-cardfile-venues' => [
      'variables' => [
      'venues' => NULL,
      ]
    ],
    'ums-cardfile-venue' => [
      'variables' => [
      'venue' => NULL,
      ]
    ],
    'ums-cardfile-events' => [
      'variables' => [
      'year' => NULL,
      'rows' => NULL,
      ]
    ],
    'ums-cardfile-event' => [
      'variables' => [
        'event' => NULL,
        'event_add_performance_form' => NULL,
      ]
    ],
  ];
}


// DRUPAL 8 MIGRATION NEW METHODS
  /*
* Debugging routine to log to the <root folder>/LWKLWK.log IN arborcat.module
*/
function dblog(...$thingsToLog) {
  $lineToLog = '';
  foreach ($thingsToLog as $item) {
    $lineToLog = $lineToLog . ' ' . print_r($item, TRUE);
  }
  // prepend date/time onto log line
  $nowDateTime = new DrupalDateTime();
  $dateTimeString = (string) $nowDateTime->format('Y-m-d H:i:s');
  $completeLine = '[' . $dateTimeString . '] ' . $lineToLog . "\n";
  error_log($completeLine, 3, "LWKLWK.log");
}

function ums_cardfile_create_link($link_text, $url) {
  $url = Url::fromUri('internal:/' . $url);
  $project_link = Link::fromTextAndUrl(t($link_text), $url);
  return $project_link->toString();
}

function ums_cardfile_write_db_record($table_name, $fields_array, $key_array) {
  $db = \Drupal::database();
  $db->merge($table_name)
  ->key($key_array)
  ->fields($fields_array)
  ->execute();
}

function ums_cardfile_drupal_goto($path, $options = []) {
  $link_text = Url::fromRoute($path, $options)->toString();
  return $link_text;
}

/*== ARTISTS =================================================================*/

function _ums_cardfile_get_artist($aid = 0) {
  dblog('_ums_cardfile_get_artist: ENTERED $aid:', $aid);
  $db = \Drupal::database();
  $artist = $db->query("SELECT ums_artists.aid AS aid, " .
                                    "ums_artists.name AS name, " .
                                    "ums_artists.name_plain AS name_plain, " .
                                    "ums_artists.alias AS alias, " .
                                    "ums_artists.notes AS notes, " .
                                    "ums_artists.photo_nid AS photo_nid " .
                                    "FROM ums_artists " .
                                    "WHERE ums_artists.aid = :aid", [':aid' => $aid])->fetchAssoc();

  // Get Works
  $works = $db->query("SELECT * " .
                  "FROM ums_artist_works, ums_work_roles, ums_works " .
                  "WHERE ums_artist_works.aid = :aid " .
                  "AND ums_artist_works.wrid = ums_work_roles.wrid " .
                  "AND ums_artist_works.wid = ums_works.wid " .
                  "ORDER BY ums_works.title ASC", [':aid' => $aid])->fetchAll(PDO::FETCH_ASSOC);
  
  foreach ($works as $work) {
    $artist['works'][] = $work;
  }

  // Get Performances
  $performances = $db->query("SELECT * " .
                  "FROM ums_artist_performances, ums_performance_roles, ums_performances, ums_events " .
                  "WHERE ums_artist_performances.aid = :aid " .
                  "AND ums_artist_performances.prid = ums_performance_roles.prid " .
                  "AND ums_artist_performances.pid = ums_performances.pid " .
                  "AND ums_performances.eid = ums_events.eid " .
                  "ORDER BY ums_events.date ASC", [':aid' => $aid])->fetchAll(PDO::FETCH_ASSOC);
  
  foreach ($performances as $perf) {
    $performance = _ums_cardfile_get_performance($perf['pid']);
    $performance['role'] = $perf['name'];
    $artist['performances'][] = $performance;
  }
  // Turn photo nid into links
  if ($artist['photo_nid']) {
    foreach (explode(',', $artist['photo_nid']) as $photo_nid) {
      $artist['photos'][] = ums_cardfile_create_link('Photo', 'node/' . $photo_nid);
    }
  }
  return $artist;
}

/*== PERFORMANCES ============================================================*/

function _ums_cardfile_get_performance($pid = 0) {
  dblog('_ums_cardfile_get_performance: ENTERED $aid:', $pid);
  $db = \Drupal::database();
  $performance = $db->query("SELECT ums_performances.pid AS pid, " .
                                    "ums_performances.eid AS eid, " .
                                    "ums_performances.wid AS wid, " .
                                    "ums_performances.notes AS notes, " .
                                    "ums_performances.youtube_url AS youtube_url," .
                                    "ums_performances.weight AS weight " .
                                    "FROM ums_performances " .
                                    "WHERE ums_performances.pid = :pid", [':pid' => $pid])->fetchAssoc();

  // Get performance event & work
  $performance['event'] = _ums_cardfile_get_event($performance['eid']);
  $performance['work'] = _ums_cardfile_get_work($performance['wid']);

  // Get performance artists
  $performance['artists'] = array();
  $perf_artists = $db->query("SELECT ums_artists.aid AS aid, " .
                  "ums_artists.name AS name, " .
                  "ums_artists.alias AS alias, " .
                  "ums_performance_roles.name AS role " .
                  "FROM ums_artist_performances, ums_artists, ums_performance_roles " .
                  "WHERE ums_artist_performances.pid = :pid " .
                  "AND ums_artist_performances.aid = ums_artists.aid " .
                  "AND ums_performance_roles.prid = ums_artist_performances.prid " .
                  "ORDER BY ums_artists.name ASC", [':pid' => $pid])->fetchAll(PDO::FETCH_ASSOC);
  
  foreach ($perf_artists as $perf_artist) {
    $performance['artists'][] = $perf_artist;
  }
  return $performance;
}

/*== EVENTS ==================================================================*/

function _ums_cardfile_get_event($eid = 0) {
  dblog('_ums_cardfile_get_event: ENTERED $eid:', $eid);
  $db = \Drupal::database();
  $event = $db->query("SELECT ums_events.eid AS eid, " .
                                   "ums_events.title AS title, " .
                                   "ums_events.date AS date, " .
                                   "ums_events.notes AS notes, " .
                                   "ums_events.program_nid AS program_nid, " .
                                   "ums_events.photo_nid AS photo_nid, " .
                                   "ums_events.youtube_url AS youtube_url," .
                                   "ums_series.sid AS sid, " .
                                   "ums_series.name AS series, " .
                                   "ums_venues.vid AS vid, " .
                                   "ums_venues.name AS venue " .
                                   "FROM ums_events, ums_series, ums_venues " .
                                   "WHERE ums_events.sid = ums_series.sid " .
                                   "AND ums_events.vid = ums_venues.vid " .
                                   "AND ums_events.eid = :eid", [':eid' => $eid])->fetchAssoc();
  // Get performances
  $performances = $db->query("SELECT * FROM ums_performances, ums_works " .
                  "WHERE ums_performances.eid = :eid " .
                  "AND ums_performances.wid = ums_works.wid " .
                  "ORDER BY ums_performances.weight ASC", [':eid' => $eid])->fetchAll(PDO::FETCH_ASSOC);

  $event['performances'] = [];
  foreach ($performances as $performance) {
    $event['performances'][] = $performance;
  }

  // Turn program nid into links
  if ($event['program_nid']) {
    foreach (explode(',', $event['program_nid']) as $program_nid) {
      $program_nid = trim($program_nid);
      if (strpos($program_nid, '#') !== FALSE) {
        $parts = explode('#', $program_nid);
        $event['programs'][] = ums_cardfile_create_link(
          'Program',
          'node/' . $parts[0],
          array('fragment' => $parts[1])
        );
      } else {
        $event['programs'][] = ums_cardfile_create_link('Program', 'node/' . $program_nid);
      }
    }
  }

  // Turn photo nid into links
  if ($event['photo_nid']) {
    foreach (explode(',', $event['photo_nid']) as $photo_nid) {
      $event['photos'][] = ums_cardfile_create_link('Photo', 'node/' . $photo_nid);
    }
  }
  return $event;
}

/*== WORKS ===================================================================*/

function _ums_cardfile_get_work($wid = 0) {
  dblog('_ums_cardfile_get_work: ENTERED $wid:', $wid);
  $db = \Drupal::database();
  $work = $db->query("SELECT ums_works.wid AS wid, " .
                                  "ums_works.title AS title, " .
                                  "ums_works.alternate AS alternate, " .
                                  "ums_works.notes AS notes, " .
                                  "ums_works.youtube_url AS youtube_url " .
                                  "FROM ums_works " .
                                  "WHERE ums_works.wid = :wid", [':wid' => $wid])->fetchAssoc();

  if ($work['wid']) {
    // Get work artists
    $work['artists'] = array();
    $work_artists = db_query("SELECT ums_artists.aid AS aid, " .
                    "ums_artists.name AS name, " .
                    "ums_artists.alias AS alias, " .
                    "ums_work_roles.name AS role " .
                    "FROM ums_artist_works, ums_artists, ums_work_roles " .
                    "WHERE ums_artist_works.wid = :wid " .
                    "AND ums_artist_works.aid = ums_artists.aid " .
                    "AND ums_work_roles.wrid = ums_artist_works.wrid " .
                    "ORDER BY ums_artists.name ASC", [':wid' => $wid])->fetchAll(PDO::FETCH_ASSOC);

    foreach ($work_artists as $work_artist) {
      $work['artists'][] = $work_artist;
    }

    // Get work events
    $work['events'] = array();
    $work_events = $db->query("SELECT ums_events.eid AS eid, " .
                    "ums_events.date AS date, " .
                    "ums_events.notes AS notes, " .
                    "ums_events.youtube_url AS youtube_url," .
                    "ums_events.program_nid AS program_nid, " .
                    "ums_events.photo_nid AS photo_nid, " .
                    "ums_series.sid AS sid, " .
                    "ums_series.name AS series, " .
                    "ums_venues.vid AS vid, " .
                    "ums_venues.name AS venue, " .
                    "ums_performances.pid AS pid " .
                    "FROM ums_events, ums_series, ums_venues, ums_performances " .
                    "WHERE ums_events.sid = ums_series.sid " .
                    "AND ums_events.vid = ums_venues.vid " .
                    "AND ums_events.eid = ums_performances.eid " .
                    "AND ums_performances.wid = :wid " .
                    "ORDER BY ums_events.date ASC", [':wid' => $wid])->fetchAll(PDO::FETCH_ASSOC);

    foreach ($work_events as $work_event) {
      $work['events'][] = $work_event;
    }
  } else {
    $work = FALSE;
  }
  return $work;
}